/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
https://projecteuler.net/problem=2
*/

var a = 1;
var b = 2;
var fibo = []

while(a <= 4e6) {
  fibo.push(a);
  var temp = a+b;
  a = b;
  b = temp;
}

console.log(fibo.filter(n => n%2 ==0).reduce((a,b)=> a+b))